# Generated by Django 2.0.6 on 2018-07-29 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTalent', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('contactInfo', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTalent', models.CharField(max_length=128)),
                ('youTubeLink', models.CharField(max_length=512)),
                ('category', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('contactInfo', models.CharField(max_length=128)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactInfo', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('userRating', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
